(NULL, 'Tarik Germoud', 'Nombres Complexes', 'Maths'),
(NULL, 'Tarik Germoud', 'Présent simple', 'Francais'),
(NULL, 'Tarik Germoud', 'La Gravité', 'Physique'),
(NULL, 'Tarik Germoud', 'Les Molécules', 'Chimie'),
(NULL, 'Tarik Germoud', 'Histoire de langue', 'Arabe'),
(NULL, 'Tarik Germoud', 'Writing course', 'Anglais'),
(NULL, 'Tarik Germoud', 'La Politique', 'Philo'),
(NULL, 'Salim Karim', 'Nombres Complexes', 'Maths'),
(NULL, 'Salim Karim', 'Présent simple', 'Francais'),
(NULL, 'Salim Karim', 'La Gravité', 'Physique'),
(NULL, 'Salim Karim', 'Les Molécules', 'Chimie'),
(NULL, 'Mehdi Benzema', 'Histoire de langue', 'Arabe'),
(NULL, 'Mehdi Benzema', 'Writing course', 'Anglais'),
(NULL, 'Mehdi Benzema', 'La Politique', 'Philo'),
(NULL, 'Mehdi Benzema', 'Nombres Complexes', 'Maths'),
(NULL, 'Mehdi Benzema', 'Présent simple', 'Francais'),
(NULL, 'Mustafa Aderdour', 'La Gravité', 'Physique'),
(NULL, 'Mustafa Aderdour', 'Les Molécules', 'Chimie'),
(NULL, 'Said Hadi', 'Histoire de langue', 'Arabe'),
(NULL, 'Said Hadi', 'Writing course', 'Anglais'),
(NULL, 'Said Hadi', 'La Politique', 'Philo'),
(NULL, 'Othmane farouk', 'Nombres Complexes', 'Maths'),
(NULL, 'Othmane farouk', 'Présent simple', 'Francais'),
(NULL, 'Aymen Damigh', 'La Gravité', 'Physique'),
(NULL, 'Mohammed Adil', 'Les Molécules', 'Chimie'),
(NULL, 'Jalil Gouchi', 'Histoire de langue', 'Arabe'),
(NULL, 'Jalil Gouchi', 'Writing course', 'Anglais'),
(NULL, 'Jalil Gouchi', 'La Politique', 'Philo')
